/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/shopping`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/collections` | `/collections`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/import` | `/import`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/collections/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/cook/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/recipe/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/shopping`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/collections` | `/collections`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/import` | `/import`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/collections/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/cook/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/recipe/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/shopping${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/collections${`?${string}` | `#${string}` | ''}` | `/collections${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/import${`?${string}` | `#${string}` | ''}` | `/import${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/shopping`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/collections` | `/collections`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/import` | `/import`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | `/collections/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/cook/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/recipe/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/collections/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/cook/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/recipe/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
